// Package icons resolves nerd-font icon names ("dev-go") to glyph runes
// and validates the icon strings persisted in circuit config.
//
// Two kinds of icon string are accepted:
//   - a nerd-font glyph name registered in nfGlyphs (e.g. "dev-go")
//   - a bare emoji or pictograph string (e.g. "🚀", "👨‍💻", "🇯🇵")
//
// Plain text is rejected. The catalog is regenerated by
// `go generate ./internal/icons/...`; see internal/icons/gen.
package icons

//go:generate go run ./gen/main.go

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/rivo/uniseg"
)

// nameRE matches a nerd-font name token (prefix-suffix). The prefix is
// 2-8 lowercase letters; the suffix is lowercase, digits, or underscore.
// Anything matching this shape MUST resolve via nfGlyphs — otherwise it
// would slip through as "emoji" and persist garbage in config.
var nameRE = regexp.MustCompile(`^[a-z]{2,8}-[a-z0-9_]+$`)

// Lookup returns the rune for a nerd-font name, or 0/false if unknown.
func Lookup(name string) (rune, bool) {
	r, ok := nfGlyphs[name]
	return r, ok
}

// Resolve renders an icon string for display:
//   - empty → ""
//   - nerd-font name → the glyph as a 1-rune string
//   - anything else → the input verbatim (caller already validated, so
//     this is the emoji path)
//
// Callers that just want to print the icon should reach for this; it
// hides the name-vs-emoji distinction.
func Resolve(s string) string {
	if s == "" {
		return ""
	}
	if r, ok := nfGlyphs[s]; ok {
		return string(r)
	}
	return s
}

// Validate accepts a stored icon value. Empty is fine (means "no icon").
// Nerd-font names must be in the catalog; anything else must be exactly
// one grapheme cluster — covers single emoji, ZWJ sequences ("👨‍💻"),
// skin tones ("👋🏽"), flag pairs ("🇯🇵"), and bare CJK glyphs ("猫").
func Validate(s string) error {
	if s == "" {
		return nil
	}
	if nameRE.MatchString(s) {
		if _, ok := nfGlyphs[s]; !ok {
			return fmt.Errorf("unknown nerd-font icon name %q (run `drift circuit icons` to browse)", s)
		}
		return nil
	}
	if uniseg.GraphemeClusterCount(s) != 1 {
		return fmt.Errorf("icon %q must be a single emoji or a known nerd-font name", s)
	}
	return nil
}

// Names returns every shipped nerd-font name, sorted ascending. Backed
// by the generated nfNames array — callers may freely range over the
// returned slice but must not mutate it.
func Names() []string {
	return nfNames[:]
}

// Search ranks shipped names by how well they match query and returns
// up to limit hits, best first. Empty query returns the first limit
// names alphabetically. Pass limit ≤ 0 for "no cap".
//
// Scoring (lower is better):
//
//	0  exact name match
//	1  prefix match
//	2  substring match — index breaks ties
//	3  subsequence match (chars in order with gaps)
//	∞  no match — dropped
//
// Within a tier, shorter names beat longer ones so "go" out-ranks
// "google_classroom" when both substring-match "go".
func Search(query string, limit int) []string {
	if query == "" {
		if limit <= 0 || limit >= len(nfNames) {
			out := make([]string, len(nfNames))
			copy(out, nfNames[:])
			return out
		}
		out := make([]string, limit)
		copy(out, nfNames[:limit])
		return out
	}
	q := strings.ToLower(query)

	type hit struct {
		name string
		tier int
		idx  int
	}
	var hits []hit
	for _, n := range nfNames {
		ln := strings.ToLower(n)
		switch {
		case ln == q:
			hits = append(hits, hit{n, 0, 0})
		case strings.HasPrefix(ln, q):
			hits = append(hits, hit{n, 1, 0})
		case strings.Contains(ln, q):
			hits = append(hits, hit{n, 2, strings.Index(ln, q)})
		default:
			if i, ok := subseqIndex(ln, q); ok {
				hits = append(hits, hit{n, 3, i})
			}
		}
	}
	sort.SliceStable(hits, func(i, j int) bool {
		a, b := hits[i], hits[j]
		if a.tier != b.tier {
			return a.tier < b.tier
		}
		if a.idx != b.idx {
			return a.idx < b.idx
		}
		if len(a.name) != len(b.name) {
			return len(a.name) < len(b.name)
		}
		return a.name < b.name
	})
	if limit > 0 && len(hits) > limit {
		hits = hits[:limit]
	}
	out := make([]string, len(hits))
	for i, h := range hits {
		out[i] = h.name
	}
	return out
}

// subseqIndex reports whether every byte of pat appears in s in order
// (gaps allowed). nfNames is ASCII so byte-level matching is correct
// and avoids the rune-decode cost. Returns the index of pat[0] in s —
// earlier first-matches rank higher.
func subseqIndex(s, pat string) (int, bool) {
	if pat == "" {
		return 0, true
	}
	si := 0
	first := -1
	for pi := 0; pi < len(pat); pi++ {
		found := false
		for ; si < len(s); si++ {
			if s[si] == pat[pi] {
				if first < 0 {
					first = si
				}
				si++
				found = true
				break
			}
		}
		if !found {
			return 0, false
		}
	}
	return first, true
}
