// Package sshconf manages drift's slice of the user's SSH setup.
//
// drift owns exactly one file end-to-end — `~/.config/drift/ssh_config` — and
// a single line (`Include ~/.config/drift/ssh_config`) that it prepends to
// `~/.ssh/config`. This package provides the parser, writer, and idempotent
// mutation helpers for that scope. It does not touch keys, identities, or any
// other part of the user's SSH configuration.
//
// All filesystem paths are passed in explicitly so callers can redirect to a
// temporary directory in tests. The package does not read `$HOME`.
package sshconf

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// IncludeDirective is the literal line drift ensures at the top of
// `~/.ssh/config`. It must match byte-for-byte so [EnsureInclude] can detect
// an already-present include and avoid duplicate writes.
const IncludeDirective = "Include ~/.config/drift/ssh_config"

// WildcardHost is the name of the per-kart wildcard block appended once at
// the end of the managed file. OpenSSH's first-match rule means literal
// `Host drift.<circuit>` blocks win for bare circuit aliases; this block
// only matches `drift.<circuit>.<kart>` targets.
const WildcardHost = "drift.*.*"

// Options configures write behavior. When Manage is false every write
// function on [Manager] becomes a no-op (the `manage_ssh_config: false`
// short-circuit).
//
// TODO: replace with config.Client once Phase 2 lands.
type Options struct {
	// Manage gates every mutating operation. When false, Ensure/Write/Remove
	// functions return nil without touching the filesystem.
	Manage bool
}

// Paths bundles the filesystem locations the Manager operates on. Separating
// them from Options lets tests point at a tempdir without threading extra
// arguments through each call.
type Paths struct {
	// UserSSHConfig is the user-owned SSH config (usually `~/.ssh/config`).
	// drift only ever prepends an `Include` line to it.
	UserSSHConfig string
	// ManagedSSHConfig is the drift-owned file (usually
	// `~/.config/drift/ssh_config`). drift writes this file in full.
	ManagedSSHConfig string
	// SocketsDir is the ControlMaster socket directory (usually
	// `~/.config/drift/sockets/`), created with mode 0700.
	SocketsDir string
}

// Manager is the entry point for the package's mutating operations. It
// bundles [Paths] and [Options] so callers don't have to thread them through
// each call.
type Manager struct {
	Paths   Paths
	Options Options
}

// New constructs a Manager. Callers are expected to fill Paths from the
// user's config; the package never resolves `$HOME` itself.
func New(paths Paths, opts Options) *Manager {
	return &Manager{Paths: paths, Options: opts}
}

// ----------------------------------------------------------------------------
// Managed-file model
// ----------------------------------------------------------------------------

// HostBlock is one `Host <name>` stanza in the managed ssh_config. Body holds
// the directive lines that follow, already indented as they should appear on
// disk (two leading spaces by convention).
type HostBlock struct {
	Name string
	Body []string
}

// managedFile is the parsed view of the drift-owned ssh_config. Header holds
// any comment/blank lines that precede the first Host block; the parser
// preserves them across rewrites so a hand-edited banner survives, even
// though the canonical file generated by this package has no header.
type managedFile struct {
	Header []string
	Blocks []HostBlock
}

// parseManaged reads the drift-managed ssh_config. A missing file is treated
// as an empty file — callers use this to bootstrap.
func parseManaged(path string) (*managedFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return &managedFile{}, nil
		}
		return nil, fmt.Errorf("sshconf: read %s: %w", path, err)
	}
	return parseManagedBytes(data), nil
}

func parseManagedBytes(data []byte) *managedFile {
	mf := &managedFile{}
	var cur *HostBlock
	scanner := bufio.NewScanner(bytes.NewReader(data))
	// Allow long lines; 1 MiB is far more than any realistic ssh_config.
	scanner.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if keyword, rest, ok := splitDirective(trimmed); ok && strings.EqualFold(keyword, "Host") {
			if cur != nil {
				mf.Blocks = append(mf.Blocks, *cur)
			}
			cur = &HostBlock{Name: rest}
			continue
		}
		if cur == nil {
			mf.Header = append(mf.Header, line)
			continue
		}
		cur.Body = append(cur.Body, line)
	}
	if cur != nil {
		mf.Blocks = append(mf.Blocks, *cur)
	}
	// Strip trailing blank lines from each block body so re-serialization is
	// stable (a block followed by blank lines and another Host would otherwise
	// accumulate blanks on every rewrite).
	for i := range mf.Blocks {
		mf.Blocks[i].Body = trimTrailingBlank(mf.Blocks[i].Body)
	}
	mf.Header = trimTrailingBlank(mf.Header)
	return mf
}

// splitDirective splits an ssh_config line into its keyword and the remainder.
// ssh_config allows `Keyword value` and `Keyword=value`; we accept either.
func splitDirective(line string) (keyword, rest string, ok bool) {
	if line == "" || strings.HasPrefix(line, "#") {
		return "", "", false
	}
	// Split on whitespace or '='.
	idx := strings.IndexAny(line, " \t=")
	if idx < 0 {
		return line, "", true
	}
	keyword = line[:idx]
	rest = strings.TrimLeft(line[idx:], " \t=")
	return keyword, rest, true
}

func trimTrailingBlank(lines []string) []string {
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

// bytes serializes the managed file. Blocks are emitted in order, separated
// by a single blank line. No trailing blank line is emitted after the last
// block so repeated round-trips are byte-stable.
func (mf *managedFile) bytes() []byte {
	var buf bytes.Buffer
	for _, h := range mf.Header {
		buf.WriteString(h)
		buf.WriteByte('\n')
	}
	if len(mf.Header) > 0 && len(mf.Blocks) > 0 {
		buf.WriteByte('\n')
	}
	for i, b := range mf.Blocks {
		if i > 0 {
			buf.WriteByte('\n')
		}
		fmt.Fprintf(&buf, "Host %s\n", b.Name)
		for _, line := range b.Body {
			buf.WriteString(line)
			buf.WriteByte('\n')
		}
	}
	return buf.Bytes()
}

// upsertBlock replaces the block with the given name in place, or appends a
// new block if no match is found. Matching is exact (ssh_config is
// case-sensitive for Host patterns).
func (mf *managedFile) upsertBlock(b HostBlock) {
	for i := range mf.Blocks {
		if mf.Blocks[i].Name == b.Name {
			mf.Blocks[i] = b
			return
		}
	}
	mf.Blocks = append(mf.Blocks, b)
}

// removeBlock drops the block with the given name if present. Returns true
// when a block was removed.
func (mf *managedFile) removeBlock(name string) bool {
	for i := range mf.Blocks {
		if mf.Blocks[i].Name == name {
			mf.Blocks = append(mf.Blocks[:i], mf.Blocks[i+1:]...)
			return true
		}
	}
	return false
}

// findBlock returns a pointer to the block with the given name, or nil.
func (mf *managedFile) findBlock(name string) *HostBlock {
	for i := range mf.Blocks {
		if mf.Blocks[i].Name == name {
			return &mf.Blocks[i]
		}
	}
	return nil
}

// ----------------------------------------------------------------------------
// Public API — managed ssh_config
// ----------------------------------------------------------------------------

// CircuitHostName returns the `Host` alias drift uses for a given circuit
// name, e.g. `drift.my-server`.
func CircuitHostName(circuit string) string {
	return "drift." + circuit
}

// WriteCircuitBlock writes (or replaces) the per-circuit Host block for the
// given circuit in the managed ssh_config. The block is emitted in the exact
// form from plans/PLAN.md § Generated Host blocks.
//
// name is the circuit's short name (the Host alias is `drift.<name>`), host
// is the DNS name or IP of the remote, and user is the SSH login. user may
// be empty to omit the User directive.
//
// When [Options.Manage] is false this is a no-op.
func (m *Manager) WriteCircuitBlock(name, host, user string) error {
	if !m.Options.Manage {
		return nil
	}
	if name == "" {
		return errors.New("sshconf: circuit name is required")
	}
	if host == "" {
		return errors.New("sshconf: host is required")
	}
	if err := ensureParentDir(m.Paths.ManagedSSHConfig); err != nil {
		return err
	}
	mf, err := parseManaged(m.Paths.ManagedSSHConfig)
	if err != nil {
		return err
	}

	block := circuitBlock(name, host, user)
	// Keep the wildcard block — if present — strictly at the end of the file
	// so OpenSSH's first-match rule favors the literal Host drift.<name>.
	var wildcard *HostBlock
	if found := mf.findBlock(WildcardHost); found != nil {
		dup := HostBlock{
			Name: found.Name,
			Body: append([]string(nil), found.Body...),
		}
		wildcard = &dup
	}
	mf.removeBlock(WildcardHost)
	mf.upsertBlock(block)
	if wildcard != nil {
		mf.Blocks = append(mf.Blocks, *wildcard)
	}
	return writeFile(m.Paths.ManagedSSHConfig, mf.bytes(), 0o600)
}

// RemoveCircuitBlock removes the per-circuit Host block for the given
// circuit if present. Missing blocks are not an error (idempotent).
//
// When [Options.Manage] is false this is a no-op.
func (m *Manager) RemoveCircuitBlock(name string) error {
	if !m.Options.Manage {
		return nil
	}
	if name == "" {
		return errors.New("sshconf: circuit name is required")
	}
	mf, err := parseManaged(m.Paths.ManagedSSHConfig)
	if err != nil {
		return err
	}
	if !mf.removeBlock(CircuitHostName(name)) {
		return nil
	}
	return writeFile(m.Paths.ManagedSSHConfig, mf.bytes(), 0o600)
}

// EnsureWildcardBlock writes the `Host drift.*.*` wildcard block at the end
// of the managed file if it is not already present. A second call is a
// no-op (the block is written exactly once across re-runs).
//
// When [Options.Manage] is false this is a no-op.
func (m *Manager) EnsureWildcardBlock() error {
	if !m.Options.Manage {
		return nil
	}
	if err := ensureParentDir(m.Paths.ManagedSSHConfig); err != nil {
		return err
	}
	mf, err := parseManaged(m.Paths.ManagedSSHConfig)
	if err != nil {
		return err
	}
	want := wildcardBlock()
	// If it exists and already matches, no write.
	if existing := mf.findBlock(WildcardHost); existing != nil && bodyEqual(existing.Body, want.Body) {
		// Ensure it's also positioned at the end. If not, reorder.
		if mf.Blocks[len(mf.Blocks)-1].Name == WildcardHost {
			return nil
		}
	}
	mf.removeBlock(WildcardHost)
	mf.Blocks = append(mf.Blocks, want)
	return writeFile(m.Paths.ManagedSSHConfig, mf.bytes(), 0o600)
}

// ListCircuits returns the circuit names (short form, without the `drift.`
// prefix) that currently have a Host block in the managed file. The wildcard
// block is excluded. Returns nil if the file is absent.
func (m *Manager) ListCircuits() ([]string, error) {
	mf, err := parseManaged(m.Paths.ManagedSSHConfig)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, b := range mf.Blocks {
		if b.Name == WildcardHost {
			continue
		}
		if strings.HasPrefix(b.Name, "drift.") {
			out = append(out, strings.TrimPrefix(b.Name, "drift."))
		}
	}
	return out, nil
}

func bodyEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// ----------------------------------------------------------------------------
// Public API — user ssh_config include line and sockets dir
// ----------------------------------------------------------------------------

// EnsureInclude guarantees that `Include ~/.config/drift/ssh_config` is the
// first non-comment, non-blank line of the file at path. If the file does
// not exist it is created with mode 0600 and the include as its only line.
// If the file exists and already contains the include as its first
// non-comment non-blank line, this is a no-op. Otherwise the include line
// is prepended; no other line in the file is edited.
//
// When [Options.Manage] is false this is a no-op.
func (m *Manager) EnsureInclude(path string) error {
	if !m.Options.Manage {
		return nil
	}
	if path == "" {
		return errors.New("sshconf: ssh config path is required")
	}
	if err := ensureParentDir(path); err != nil {
		return err
	}
	data, err := os.ReadFile(path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		return writeFile(path, []byte(IncludeDirective+"\n"), 0o600)
	case err != nil:
		return fmt.Errorf("sshconf: read %s: %w", path, err)
	}
	if hasIncludeAtTop(data) {
		return nil
	}
	var buf bytes.Buffer
	buf.WriteString(IncludeDirective)
	buf.WriteByte('\n')
	// Preserve the existing file byte-for-byte after the prepended line.
	// Add a separating newline only if the original file doesn't start with
	// one already (avoids doubling blank lines on repeated appends).
	buf.Write(data)
	return writeFile(path, buf.Bytes(), 0o600)
}

// hasIncludeAtTop reports whether the first non-comment, non-blank line of
// data is exactly the drift include directive.
func hasIncludeAtTop(data []byte) bool {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		return line == IncludeDirective
	}
	return false
}

// EnsureSocketsDir creates the ControlMaster sockets directory with mode
// 0700 if it does not already exist. If the directory already exists its
// mode is tightened to 0700 — ssh will refuse to use the socket directory if
// it's group- or world-writable.
//
// When [Options.Manage] is false this is a no-op.
func (m *Manager) EnsureSocketsDir() error {
	if !m.Options.Manage {
		return nil
	}
	path := m.Paths.SocketsDir
	if path == "" {
		return errors.New("sshconf: sockets dir path is required")
	}
	if err := os.MkdirAll(path, 0o700); err != nil {
		return fmt.Errorf("sshconf: create %s: %w", path, err)
	}
	// MkdirAll does not chmod an existing directory; enforce 0700 explicitly
	// so a pre-existing 0755 dir is tightened.
	if err := os.Chmod(path, 0o700); err != nil { //nolint:gosec // G302: path is a directory; 0700 is the intended mode.
		return fmt.Errorf("sshconf: chmod %s: %w", path, err)
	}
	return nil
}

// ----------------------------------------------------------------------------
// Block templates
// ----------------------------------------------------------------------------

// circuitBlock returns the canonical per-circuit HostBlock for the given
// parameters, matching plans/PLAN.md § Generated Host blocks byte-for-byte.
func circuitBlock(name, host, user string) HostBlock {
	body := []string{
		"  HostName " + host,
	}
	if user != "" {
		body = append(body, "  User "+user)
	}
	body = append(body,
		"  ControlMaster auto",
		"  ControlPath ~/.config/drift/sockets/cm-%r@%h:%p",
		"  ControlPersist 10m",
		"  ServerAliveInterval 30",
		"  ServerAliveCountMax 3",
	)
	return HostBlock{Name: CircuitHostName(name), Body: body}
}

// wildcardBlock returns the canonical per-kart wildcard HostBlock.
func wildcardBlock() HostBlock {
	return HostBlock{
		Name: WildcardHost,
		Body: []string{
			"  ProxyCommand drift ssh-proxy %h %p",
			"  ControlMaster auto",
			"  ControlPath ~/.config/drift/sockets/cm-%r@%h:%p",
			"  ControlPersist 10m",
		},
	}
}

// ----------------------------------------------------------------------------
// File helpers
// ----------------------------------------------------------------------------

// writeFile writes data to path atomically via a rename from a temp file in
// the same directory. This guards against leaving a half-written ssh_config
// if the process is interrupted mid-write — ssh would otherwise refuse to
// parse the truncated file on the next invocation.
func writeFile(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".drift-sshconf-*")
	if err != nil {
		return fmt.Errorf("sshconf: create temp in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }() // no-op on success (rename moved it)
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sshconf: write %s: %w", tmpPath, err)
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sshconf: chmod %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("sshconf: close %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("sshconf: rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

func ensureParentDir(path string) error {
	dir := filepath.Dir(path)
	if dir == "" || dir == "." {
		return nil
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("sshconf: create %s: %w", dir, err)
	}
	return nil
}
