#!/usr/bin/env bash
# Dump lakitu's JSON-RPC wire surface as a single markdown reference.
# Output goes to stdout; redirect to docs/lakitu-rpc.md.
#
# Authoritative sources we pull from:
#   - internal/wire/methods.go   (method name catalog; edit this file to
#                                 add/rename a method)
#   - internal/wire/wire.go      (Request/Response types, transport notes)
#   - internal/rpcerr/rpcerr.go  (error code + type taxonomy)
#   - lakitu help                (already renders RPC METHODS + EXIT CODES
#                                 from the same sources)

set -euo pipefail

GO="${GO:-}"
if [[ -z "$GO" ]]; then
  if command -v go >/dev/null 2>&1; then
    GO=go
  else
    GO=$(ls /nix/store/*-go-*/bin/go 2>/dev/null | head -1 || true)
  fi
fi
if [[ -z "$GO" || ! -x "$GO" ]]; then
  echo "dump_rpc.sh: could not locate 'go' on PATH or under /nix/store" >&2
  exit 1
fi

repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$repo_root"

lakitu_help=$("$GO" run ./cmd/lakitu help 2>&1 || true)

# Extract a section (lines under a header in all-caps, until the next
# all-caps header or EOF). Preserves the body verbatim.
extract_section() {
  local header="$1"
  awk -v hdr="$header" '
    $0 == hdr { in_sec = 1; next }
    in_sec && /^[A-Z][A-Z ()]*$/ { exit }
    in_sec { print }
  ' <<<"$lakitu_help"
}

rpc_methods=$(extract_section "RPC METHODS" | sed '/^$/d')
exit_codes=$(extract_section "EXIT CODES" | sed '/^$/d')

# Error taxonomy: grep the Type constants out of rpcerr.go. The file's
# own comment tells clients to prefer Type over Code for branching, so
# the doc should surface it prominently.
error_types=$(awk '
  /^const \(/ { in_block = 1; next }
  in_block && /^\)/ { in_block = 0; next }
  in_block && $2 == "Type" && $3 == "=" {
    name = $1
    val = $4
    gsub(/"/, "", val)
    printf("  %-28s %s\n", val, name)
  }
' internal/rpcerr/rpcerr.go)

cat <<'HDR'
# lakitu JSON-RPC reference

This file is generated by `.claude/skills/drift-docs/scripts/dump_rpc.sh`.
Do not edit by hand — run the drift-docs skill to regenerate.

lakitu is the server half of drift. drift speaks to it over plain SSH using
a one-shot JSON-RPC 2.0 protocol: one request in on stdin, one response out
on stdout, SSH exits. State lives on the circuit under `~/.drift/garage/`.

---

## Transport

- **Framing**: one JSON object per invocation, newline-terminated. No
  batches, no notifications (every request must carry an `id`).
- **Params**: named params only — positional arrays are rejected at decode
  time.
- **Version**: `jsonrpc: "2.0"` required on both request and response.
- **Trigger**: `ssh <circuit> lakitu rpc < request.json` (the `rpc`
  subcommand reads stdin, dispatches, writes one response, exits).

### Request

```json
{
  "jsonrpc": "2.0",
  "method": "kart.list",
  "params": {},
  "id": 1
}
```

### Response (success)

```json
{
  "jsonrpc": "2.0",
  "result": { "...": "method-specific" },
  "id": 1
}
```

### Response (error)

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": 3,
    "message": "kart \"foo\" not found",
    "data": { "type": "kart_not_found", "kart": "foo" }
  },
  "id": 1
}
```

See `internal/wire/wire.go` for the exact Request/Response Go types and
the decoder's validation rules.

---

## Version compatibility

Every drift invocation probes `server.version` first. The response carries
a semver `version` string and an integer `api` field that bumps on breaking
wire changes. drift's policy:

| mismatch          | behavior       |
|-------------------|----------------|
| major version     | error, abort   |
| minor version     | warn to stderr |
| patch version     | silent         |
| `api` mismatch    | error, abort   |

Bypass during upgrades with `drift --skip-version-check …`.

`server.info` is the richer setup-time variant (same version fields plus
circuit identity and default character). Reserved for `drift init` and
`drift circuit add`; it is not on the hot path.

---

## Methods

The canonical list lives in `internal/wire/methods.go`. Every method
constant there is registered on the server in `internal/server/server.go`
or `internal/server/kart.go`. The lakitu CLI renders the same catalog via
`drift help --full` and `lakitu help`.

```text
HDR
printf '%s\n' "$rpc_methods"
cat <<'HDR'
```

For each method's request/response shape, read the handler — handlers are
named `<Method>Handler` in `internal/server/`, e.g. `kart.list` lives in
`internal/server/kart.go` as `KartListHandler`.

---

## Errors

Errors serialize as the standard JSON-RPC error object with `code`,
`message`, and an optional `data` payload. Exit codes on the human CLI
path mirror `code`.

```text
HDR
printf '%s\n' "$exit_codes"
cat <<'HDR'
```

Clients should branch on `data.type` rather than `code` — the type is a
stable snake_case identifier, whereas `code` is coarse. Current types:

```text
HDR
printf '%s\n' "$error_types"
cat <<'HDR'
```

Some handlers attach extra context under well-known `data` keys (see
`internal/rpcerr/rpcerr.go`):

- `devpod_stderr` — captured devpod stderr tail on `devpod_*` errors
- `devpod_stdout` — captured devpod stdout (devpod relays most real
  failure messages here, not stderr)

Additional arbitrary keys may appear per error type (e.g. `kart_not_found`
attaches `kart` and `circuit`). Clients should tolerate unknown keys.
HDR
