#!/usr/bin/env bash
# Dump the drift CLI surface as a single markdown reference.
# Output goes to stdout; redirect to docs/drift-cli.md.
#
# Walks every subcommand discovered from `drift --help` (including nested
# ones like `circuit set default`) and captures its `--help` verbatim.
#
# Go may not be on $PATH on NixOS dev shells — fall back to the nix store.

set -euo pipefail

GO="${GO:-}"
if [[ -z "$GO" ]]; then
  if command -v go >/dev/null 2>&1; then
    GO=go
  else
    GO=$(ls /nix/store/*-go-*/bin/go 2>/dev/null | head -1 || true)
  fi
fi
if [[ -z "$GO" || ! -x "$GO" ]]; then
  echo "dump_cli.sh: could not locate 'go' on PATH or under /nix/store" >&2
  exit 1
fi

repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$repo_root"

drift() { "$GO" run ./cmd/drift "$@" 2>&1; }

# Extract command paths from a Kong "Commands:" block, relative to a
# parent prefix. Kong lines look like:
#   "  circuit set default [<name>]"
#   "  connect (into,attach) <name> [flags]"
# We want the path tokens only, dropping positional args / flag hints
# that start with <, [, or (.
extract_children() {
  local parent="$1"
  awk -v parent="$parent" '
    function is_word(tok) { return tok ~ /^[a-z][a-z0-9_-]*$/ }
    /^Commands:/ { in_cmds = 1; next }
    in_cmds && /^[^ ]/ { in_cmds = 0 }
    in_cmds && /^  [a-z]/ {
      line = $0
      sub(/^  /, "", line)
      n = split(line, parts, " ")
      # Keep only the leading run of word tokens — the path. Stop at the
      # first arg/flag/alias placeholder like "<name>", "[flags]",
      # "(into,attach)", or ellipses.
      path_n = 0
      for (i = 1; i <= n; i++) {
        if (is_word(parts[i])) path_n = i; else break
      }
      if (path_n == 0) next
      # Drop the parent prefix if present.
      prefix_len = parent == "" ? 0 : split(parent, pp, " ")
      if (prefix_len > 0) {
        for (i = 1; i <= prefix_len; i++) {
          if (parts[i] != pp[i]) { prefix_len = 0; break }
        }
      }
      out = ""
      for (i = prefix_len + 1; i <= path_n; i++) {
        out = (out == "" ? parts[i] : out " " parts[i])
      }
      if (out != "") print out
    }
  ' | sort -u
}

# BFS through the command tree. Visited commands are printed; new
# children are enqueued.
declare -a queue=("")   # empty string = root
declare -A seen=()
declare -a order=()

top_help=$(drift --help || true)

enqueue_children() {
  local parent="$1" help_text="$2"
  while read -r child; do
    [[ -z "$child" ]] && continue
    local full
    if [[ -z "$parent" ]]; then
      full="$child"
    else
      full="$parent $child"
    fi
    if [[ -z "${seen[$full]:-}" ]]; then
      seen[$full]=1
      order+=("$full")
      queue+=("$full")
    fi
  done < <(printf '%s\n' "$help_text" | extract_children "$parent")
}

enqueue_children "" "$top_help"

# Process queue: root is already handled; keep discovering deeper levels.
i=1
while (( i < ${#queue[@]} )); do
  cmd="${queue[$i]}"
  help_text=$(drift $cmd --help 2>&1 || true)
  enqueue_children "$cmd" "$help_text"
  ((i++))
done

# Header + top-level usage.
cat <<'HDR'
# drift CLI reference

This file is generated by `.claude/skills/drift-docs/scripts/dump_cli.sh`.
Do not edit by hand — run the drift-docs skill to regenerate.

---

## `drift --help`

```text
HDR
printf '%s\n' "$top_help"
cat <<'HDR'
```

## `drift help --full`

```text
HDR
drift help --full || true
cat <<'HDR'
```

## Subcommands

HDR

for cmd in "${order[@]}"; do
  printf '### `drift %s --help`\n\n```text\n' "$cmd"
  drift $cmd --help 2>&1 || true
  printf '```\n\n'
done
